version: 0.2

phases:
  install:
    commands:
      - echo "Installation..."

  pre_build:
    commands:
      - echo "Pré-build..."

  build:
    commands:
      - echo "Build..."

  post_build:
    commands:
      - echo "Déploiement vers S3..."
      - aws s3 cp . s3://abd-devops/ --recursive

artifacts:
  files:
    - '**/*'